GRANT USAGE ON SCHEMA public TO SYS_USER_POLICY;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO SYS_USER_POLICY;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO SYS_USER_POLICY;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO SYS_USER_POLICY;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO SYS_USER_POLICY;